# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'Example' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Example
  pod 'RoverCampaigns/Notifications', :path => '../'
  pod 'RoverCampaigns/Location', :path => '../'
  pod 'RoverCampaigns/Bluetooth', :path => '../'
  pod 'RoverCampaigns/Debug', :path => '../'
  pod 'RoverCampaigns/Telephony', :path => '../'
  pod 'RoverCampaigns/AdSupport', :path => '../'
  pod 'RoverCampaigns/Ticketmaster', :path => '../'
end

target 'NotificationService' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NotificationService
  pod 'RoverAppExtensions', :path => '../'
end
